#!/bin/bash

source "$(dirname "${BASH_SOURCE[0]}")/scripts-lib.sh"

declare -A MANIFEST_PATHS=(
	["Default"]="$HOME/.local/share/Steam/steamapps"
	["SSD"]="/mnt/ssd/SteamLibrary/steamapps"
)

display_path_list() {
	for steam_path in "${!MANIFEST_PATHS[@]}"; do
		echo -e "${C_RED}Steam Prefix: ${MANIFEST_PATHS[$steam_path]}:${C_NC} \n"

		for file in "${MANIFEST_PATHS[$steam_path]}"/appmanifest_*.acf; do
			appid=$(awk -F'"' '/"appid"[[:space:]]+"[0-9]+"/ {print $4}' "$file")
			name=$(awk -F'"' '/"name"[[:space:]]+"[^"]+"/ {print $4}' "$file")

			# Check if both values are non-empty
			if [[ -n "$appid" && -n "$name" ]]; then
				echo -e "Game: $name"
				echo -e "${C_BLUE}Prefix${C_NC}: ${MANIFEST_PATHS[$steam_path]}/compatdata/$appid"
				echo -e "${C_GREEN}Prefix User${C_NC}: ${MANIFEST_PATHS[$steam_path]}/compatdata/$appid/pfx/drive_c/users/steamuser\n"
			fi
		done
	done
}

display_path_list
