### ~/.config/MangoHud/MangoHud.conf

### Hud
width=260
# height=140
cellpadding_y=-0.085
legacy_layout=false
table_columns=3
horizontal=false
background_alpha=0.4
round_corners=8
font_size=18
position=top-left
hud_no_margin=0
toggle_hud=Shift_R+F12
toggle_hud_position=Shift_R+F11
# toggle_preset=Shift_R+F10
# toggle_fps_limit=Shift_L+F1
# toggle_logging=Shift_L+F2
# reload_cfg=Shift_L+F4
# upload_log=Shift_L+F3
# reset_fps_metrics=Shift_R+F9

### Time
time
time_format=%T

### Version
# version

### GPU
gpu_stats
gpu_text=GPU
gpu_temp
# gpu_junction_temp
gpu_core_clock
gpu_mem_temp
gpu_mem_clock
gpu_power
gpu_power_limit
gpu_load_change
gpu_load_value=60,90
gpu_load_color=39F900,FDFD09,B22222
# GPU fan in rpm on AMD, FAN in percent on NVIDIA
gpu_fan
# gpu_voltage only works on AMD GPUs
gpu_voltage
# Select list of GPUs to display
# gpu_list=0,1
# gpu_efficiency

### CPU
cpu_text=CPU
cpu_color=2E97CB
cpu_stats
cpu_load_change
cpu_load_color=39F900,FDFD09,B22222
cpu_temp
cpu_mhz
cpu_power
# cpu_efficiency

### IO
io_read
io_write

### VRAM / RAM
vram
gpu_mem_temp
gpu_mem_clock
ram
ram_color=C26693
procmem
procmem_shared
procmem_virt

### Vulkan / driver info
vulkan_driver
gpu_name
wine
# arch

### FPS / frametime
fps
fps_color_change
fps_sampling_period=500
fps_metrics=avg,0.01,0.001
fps_value=30,60
fps_color=B22222,FDFD09,39F900
frame_timing
frame_timing_detailed
frametime

### Display GPU throttling status based on Power, current, temp or "other"
## Only shows if throttling is currently happening
throttling_status=0
## Same as throttling_status but displays throttling on the frametime graph
throttling_status_graph=0

### Extra status lines
frame_count
gamemode
vkbasalt
resolution
present_mode
display_server
offset_x=0

### Gamescope related options
## Display the status of FSR (only works in gamescope)
# fsr
## Hides the sharpness info for the `fsr` option (only available in gamescope)
# hide_fsr_sharpness
## Shows the graph of gamescope app frametimes and latency (only on gamescope obviously)
# debug
## Display the status of HDR (only works in gamescope)
# hdr
## Display the current refresh rate (only works in gamescope)
# refresh_rate