#!/bin/bash

declare -A DNS_SERVERS=(
    ["Electro"]="78.157.42.100,78.157.42.101"
    ["403"]="10.202.10.202,10.202.10.102"
    ["Shecan"]="178.22.122.100,185.51.200.2"
    ["Begzar"]="185.55.226.26,185.55.225.25"
    ["Google"]="8.8.8.8,8.8.4.4"
    ["Cloudflare"]="1.1.1.1"
)

display_dns_list() {
    echo "Available DNS Servers:"
    local i=1
    for dns_name in "${!DNS_SERVERS[@]}"; do
        echo "$i. $dns_name: (${DNS_SERVERS[$dns_name]})"
        ((i++))
    done
}

select_dns() {
    local input
    read -p "Select a DNS server (enter the name or number): " input

    if [[ $input =~ ^[0-9]+$ ]]; then
        local dns_index=1
        for dns_name in "${!DNS_SERVERS[@]}"; do
            if ((dns_index == input)); then
                echo "$dns_name"
                return
            fi
            ((dns_index++))
        done
    else
        if [[ -n ${DNS_SERVERS[$input]} ]]; then
            echo "$input"
            return
        fi
    fi

    echo "Invalid selection. Please try again." >&2
    select_dns
}

update_resolv_conf() {
    local selected_dns="$1"
    sudo bash -c "echo '' > /etc/resolv.conf"
    IFS=',' read -ra dns_array <<<"$selected_dns"
    for dns in "${dns_array[@]}"; do
        echo "nameserver $dns" | sudo tee -a /etc/resolv.conf >/dev/null
    done
    echo "Updated /etc/resolv.conf with DNS servers: $selected_dns"
}

display_dns_list
selected_name=$(select_dns)
update_resolv_conf "${DNS_SERVERS[$selected_name]}"
