#!/bin/bash

# SERVER="nl25.apibaz.info"
# SERVER="iosmtn.apibaz.info"
# SERVER="mci1.apibaz.info"
# SERVER="newnl.apibaz.info"
# SERVER="en1.apibaz.info"
# SERVER="en2.apibaz.info"
# SERVER="mcis8.apibaz.info"
# SERVER="mciwin.apibaz.info"
# SERVER="mciwin.apibaz.info"
# SERVER="vps-2dbe0949.vps.ovh.net"
SERVER="vps-1b59076c.vps.ovh.net"
USER="vbaz568161"
PASSWORD="2489"

main() {
    echo "Connecting to VPN at $SERVER as $USER..."

    sudo openconnect --server="$SERVER" --user="$USER" --no-dtls <<END
yes
$PASSWORD
END
}

main
