#!/bin/bash

USER="vbaz568161"
PASSWORD="2489"

declare -A VPN_SERVERS=(
    ["FR"]="vps-1b59076c.vps.ovh.net"
    ["Us"]="us.apibaz.info"
    ["Finland"]="finland.apibaz.info"
    ["Poland"]="poland.apibaz.info"
    ["Emarat"]="emarat.apibaz.info"
    ["Singapore"]="singapore.apibaz.info"
    ["NewNl"]="newnl.apibaz.info"
    ["EN 1"]="en1.apibaz.info"
    ["EN 2"]="en2.apibaz.info"
)

display_vpn_list() {
    echo "Available VPN Servers:"
    local i=1
    for vpn_name in "${!VPN_SERVERS[@]}"; do
        echo -e "$i. $vpn_name: (${VPN_SERVERS[$vpn_name]})"
        ((i++))
    done
}

select_vpn_server() {
    local input
    read -p "Select a VPN server (enter the name or number): " input

    if [[ $input =~ ^[0-9]+$ ]]; then
        local vpn_index=1
        for vpn_name in "${!VPN_SERVERS[@]}"; do
            if ((vpn_index == input)); then
                echo "$vpn_name"
                return
            fi
            ((vpn_index++))
        done
    else
        if [[ -n ${VPN_SERVERS[$input]} ]]; then
            echo "$input"
            return
        fi
    fi

    echo "Invalid selection. Please try again." >&2
    select_vpn_server
}

connect_vpn() {
    local server="$1"
    echo "Connecting to VPN at $server as $USER..."

    sudo openconnect --server="$server" --user="$USER" --no-dtls <<END
yes
$PASSWORD
END
}

main() {
    display_vpn_list
    local selected_name=$(select_vpn_server)
    connect_vpn "${VPN_SERVERS[$selected_name]}"
}

main
