abbr void-pkgs "cd $VOID_PACKAGES_PATH"
abbr vshutdown "sudo shutdown -h now"
abbr vreboot "sudo reboot"
abbr vrepos "xbps-query -L"
abbr vpkgf "xbps-query -f"
abbr vpkg "sudo xbps-install"
abbr vup "sudo xbps-install -Su"
abbr vrm "sudo xbps-remove -R"
abbr vsearch "xbps-query -Rs"
abbr vinfo "xbps-query -S"
abbr vlocate "xbps-query -f"
abbr vlist "xbps-query -l"
abbr vhold "sudo xbps-pkgdb -m hold"
abbr vunhold "sudo xbps-pkgdb -m unhold"
abbr vmirror "sudo xmirror"
abbr vcp "sudo xbps-remove -O"
abbr vch "echo 'Clean: all cache packages' && sudo rm /var/cache/xbps/*"
abbr svservices "ls /etc/sv/"
abbr svlist "ls -la /var/service/"
abbr svreset "sudo sv restart"
abbr svstatus "sudo sv status"
abbr svon "sudo sv up"
abbr svoff "sudo sv down"
abbr killer "pkill -f"
abbr psfind "ps -aux | grep"
