alias flist="flatpak list"
alias fclean="flatpak uninstall --unused --delete-data"
alias fpkg="flatpak install flathub"
alias frm="flatpak uninstall flathub"
alias fup="flatpak update"
alias fsearch="flatpak search"
alias fdir="cd $HOME/.var/app && ls"
