#!/bin/bash

USER="afz2077"
PASSWORD="6764"

declare -A VPN_SERVERS=(
    ["MCI"]="news2.apibaz.org"
    ["Server NL 1"]="nl2.apibaz.org"
    ["Server NL 2"]="nl3.apibaz.org"
    ["Server NL 3"]="nl4.apibaz.org"
    ["Server NL 4"]="nl5.apibaz.org"
    ["Server NL 5"]="nl6.apibaz.org"
    ["Server NL 6"]="nl7.apibaz.org"
    ["Server NL 7"]="nl8.apibaz.org"
    ["Server NL 8"]="nl9.apibaz.org"
)

display_vpn_list() {
    echo "Available VPN Servers:"
    local i=1
    for vpn_name in "${!VPN_SERVERS[@]}"; do
        echo -e "$i. $vpn_name: (${VPN_SERVERS[$vpn_name]})"
        ((i++))
    done
}

select_vpn_server() {
    local input
    read -p "Select a VPN server (enter the name or number): " input

    if [[ $input =~ ^[0-9]+$ ]]; then
        local vpn_index=1
        for vpn_name in "${!VPN_SERVERS[@]}"; do
            if ((vpn_index == input)); then
                echo "$vpn_name"
                return
            fi
            ((vpn_index++))
        done
    else
        if [[ -n ${VPN_SERVERS[$input]} ]]; then
            echo "$input"
            return
        fi
    fi

    echo "Invalid selection. Please try again." >&2
    select_vpn_server
}

connect_vpn() {
    local server="$1"
    echo "Connecting to VPN at $server as $USER..."

    sudo openconnect --server="$server" --user="$USER" --no-dtls <<END
yes
$PASSWORD
END
}

main() {
    display_vpn_list
    local selected_name=$(select_vpn_server)
    connect_vpn "${VPN_SERVERS[$selected_name]}"
}

main
